on: [push]
name: Run Tests

jobs:
  check:
    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: foundry-toolchain
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run tests
        run: forge test -vvv        
        env:
          CELER_FUJI_ADDRESS: '0xE9533976C590200E32d95C53f06AE12d292cFc47'
